server:
  port: 8769 # 8768
spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/tearzhao/repo_zyl_demo_springcloud_v203.git # https://github.com/cralor7/springcloud
          search-paths: config-repo
         # username:
         # password:
          default-label: master
    bus:
      trace:
        enabled: true
      enabled: true
  rabbitmq:
    host: 10.88.1.4 # ${rabbitmq.host}
    port: 5672
    username: guest
    password: guest
    #virtual-host: ${rabbitmq.i5x.vhost}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
      expose: "*"
    refresh:
      enabled: true